title: Aleksandra Stamper
description: >
  <img src="/images/02-Aleksandra Stamper-1920.jpg" width="120" style="border-radius: 50%; margin-bottom: 10px;"><br>
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
